module.exports = {
  65005: require('./totalEnergy.js')('ac'),
  65006: require('./reactivePower.js')('ac', 'C'),
  65007: require('./power.js')('ac', 'C'),
  65008: require('./quantities.js')('ac', 'C'),
  65009: require('./reactivePower.js')('ac', 'B'),
  65010: require('./power.js')('ac', 'B'),
  65011: require('./quantities.js')('ac', 'B'),
  65012: require('./reactivePower.js')('ac', 'A'),
  65013: require('./power.js')('ac', 'A'),
  65014: require('./quantities.js')('ac', 'A'),
  65015: require('./reactivePower.js')('ac', 'total'),
  65016: require('./power.js')('ac', 'total'),
  65017: require('./quantities.js')('ac', 'average'),
  65018: require('./totalEnergy.js')('generator'),
  65019: require('./reactivePower.js')('generator', 'C'),
  65020: require('./power.js')('generator', 'C'),
  65021: require('./quantities.js')('generator', 'C'),
  65022: require('./reactivePower.js')('generator', 'B'),
  65023: require('./power.js')('generator', 'B'),
  65024: require('./quantities.js')('generator', 'B'),
  65025: require('./reactivePower.js')('generator', 'A'),
  65026: require('./power.js')('generator', 'A'),
  65027: require('./quantities.js')('generator', 'A'),
  65028: require('./reactivePower.js')('generator', 'total'),
  65029: require('./power.js')('generator', 'total'),
  65030: require('./quantities.js')('generator', 'average'),
}
