module.exports = {
  65005: require('./totalEnergy.js')('ac'),
  65006: require('./reactivePower.js')('ac', 'phase.C'),
  65007: require('./power.js')('ac', 'phase.C'),
  65008: require('./quantities.js')('ac', 'phase.C'),
  65009: require('./reactivePower.js')('ac', 'phase.B'),
  65010: require('./power.js')('ac', 'phase.B'),
  65011: require('./quantities.js')('ac', 'phase.B'),
  65012: require('./reactivePower.js')('ac', 'phase.A'),
  65013: require('./power.js')('ac', 'phase.A'),
  65014: require('./quantities.js')('ac', 'phase.A'),
  65015: require('./reactivePower.js')('ac', 'total'),
  65016: require('./power.js')('ac', 'total'),
  65017: require('./quantities.js')('ac', 'average'),
  65018: require('./totalEnergy.js')('generators'),
  65019: require('./reactivePower.js')('generators', 'phase.C'),
  65020: require('./power.js')('generators', 'phase.C'),
  65021: require('./quantities.js')('generators', 'phase.C'),
  65022: require('./reactivePower.js')('generators', 'phase.B'),
  65023: require('./power.js')('generators', 'phase.B'),
  65024: require('./quantities.js')('generators', 'phase.B'),
  65025: require('./reactivePower.js')('generators', 'phase.A'),
  65026: require('./power.js')('generators', 'phase.A'),
  65027: require('./quantities.js')('generators', 'phase.A'),
  65028: require('./reactivePower.js')('generators', 'total'),
  65029: require('./power.js')('generators', 'total'),
  65030: require('./quantities.js')('generators', 'average'),
}
